name: types

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: types-${{ github.head_ref }}
  cancel-in-progress: true

env:
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"

jobs:
  run:
    name: Check types with mypy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install Hatch
        run: pip install --upgrade hatch

      - name: Run linter
        run: hatch run types:check
